### Upload image (multipart)
POST http://localhost:10330/api/minio/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="imageType"

BOOK
--WebAppBoundary
Content-Disposition: form-data; name="id"

123
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sample.png"
Content-Type: image/png

< ../src/test/resources/sample.jpg
--WebAppBoundary--

###

### Get image URLs (form-urlencoded)
GET http://localhost:10330/api/minio/images
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="imageType"

BOOK
--WebAppBoundary
Content-Disposition: form-data; name="id"

123
